create table public.provinces (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  display_order integer not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  constraint provinces_name_not_blank check (btrim(name) <> ''),
  constraint provinces_slug_not_blank check (btrim(slug) <> '')
);

insert into public.provinces (name, slug, display_order)
values
  ('Pinar del Rio', 'pinar-del-rio', 1),
  ('Artemisa', 'artemisa', 2),
  ('La Habana', 'la-habana', 3),
  ('Mayabeque', 'mayabeque', 4),
  ('Matanzas', 'matanzas', 5),
  ('Cienfuegos', 'cienfuegos', 6),
  ('Villa Clara', 'villa-clara', 7),
  ('Sancti Spiritus', 'sancti-spiritus', 8),
  ('Ciego de Avila', 'ciego-de-avila', 9),
  ('Camaguey', 'camaguey', 10),
  ('Las Tunas', 'las-tunas', 11),
  ('Holguin', 'holguin', 12),
  ('Granma', 'granma', 13),
  ('Santiago de Cuba', 'santiago-de-cuba', 14),
  ('Guantanamo', 'guantanamo', 15),
  ('Isla de la Juventud', 'isla-de-la-juventud', 16)
on conflict (slug) do nothing;

alter table public.provinces enable row level security;
alter table public.provinces force row level security;

create policy "Public can read provinces"
on public.provinces
for select
to public
using (true);

alter table public.business_catalogs
  add column address text,
  add column phone text,
  add column website_url text,
  add column facebook_url text,
  add column instagram_url text,
  add column whatsapp_url text,
  add column province_id bigint references public.provinces (id) on delete set null;

create index business_catalogs_province_id_idx
  on public.business_catalogs (province_id);

create index business_catalogs_active_created_at_idx
  on public.business_catalogs (is_active, created_at desc);

comment on table public.provinces is 'Lookup table for catalog provinces.';
comment on column public.business_catalogs.address is 'Business street address or reference point.';
comment on column public.business_catalogs.phone is 'Primary contact phone for the business.';
comment on column public.business_catalogs.website_url is 'Optional public website for the business catalog.';
comment on column public.business_catalogs.facebook_url is 'Optional Facebook profile or page for the business catalog.';
comment on column public.business_catalogs.instagram_url is 'Optional Instagram profile for the business catalog.';
comment on column public.business_catalogs.whatsapp_url is 'Optional WhatsApp direct contact link for the business catalog.';
comment on column public.business_catalogs.province_id is 'Province associated with the business catalog.';
