create table public.business_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  display_order integer not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  constraint business_categories_name_not_blank check (btrim(name) <> ''),
  constraint business_categories_slug_not_blank check (btrim(slug) <> '')
);

insert into public.business_categories (name, slug, display_order)
values
  ('Tecnologia', 'tecnologia', 1),
  ('Moda y accesorios', 'moda-y-accesorios', 2),
  ('Belleza y cuidado personal', 'belleza-y-cuidado-personal', 3),
  ('Hogar y decoracion', 'hogar-y-decoracion', 4),
  ('Alimentos y bebidas', 'alimentos-y-bebidas', 5),
  ('Salud y farmacia', 'salud-y-farmacia', 6),
  ('Ferreteria y construccion', 'ferreteria-y-construccion', 7),
  ('Papeleria y oficina', 'papeleria-y-oficina', 8),
  ('Servicios profesionales', 'servicios-profesionales', 9),
  ('Mascotas', 'mascotas', 10),
  ('Deportes y fitness', 'deportes-y-fitness', 11),
  ('Otros', 'otros', 12)
on conflict (slug) do nothing;

alter table public.business_categories enable row level security;
alter table public.business_categories force row level security;

create policy "Public can read business categories"
on public.business_categories
for select
to public
using (true);

alter table public.business_catalogs
  add column business_category_id bigint references public.business_categories (id) on delete set null;

create index business_catalogs_business_category_id_idx
  on public.business_catalogs (business_category_id);

alter table public.business_catalogs
  drop column if exists website_url;

comment on table public.business_categories is 'Lookup table for business catalog categories.';
comment on column public.business_catalogs.business_category_id is 'Category associated with the business catalog.';
